local o = vim.opt
local g = vim.g

o.guicursor = ""
o.mouse = "a"
o.cursorline = true
o.completeopt = { "menuone", "noselect" }
o.clipboard = "unnamedplus"
o.fileencoding = "utf-8"
o.number = true
o.relativenumber = true
o.fillchars = { eob = " " }
o.tabstop = 4
o.softtabstop = 4
o.shiftwidth = 4
o.expandtab = true
o.hlsearch = false
o.incsearch = true
o.copyindent = true
o.smartindent = true
o.wrap = false
o.history = 100
o.ignorecase = true
o.laststatus = 3
o.lazyredraw = true
o.preserveindent = true
o.pumheight = 10
o.scrolloff = 8
o.signcolumn = "yes"
o.smartcase = true
o.splitbelow = true
o.splitright = true
o.swapfile = false
o.termguicolors = true
o.timeoutlen = 300
o.undofile = true
o.updatetime = 300
o.writebackup = false

g.mapleader = " "
g.do_filetype_lua = 1
g.did_load_filetypes = 0
g.highlighturl_enabled = true
g.zipPlugin = false
g.load_black = false
g.loaded_2html_plugin = true
g.loaded_getscript = true
g.loaded_getscriptPlugin = true
g.loaded_gzip = true
g.loaded_logipat = true
g.loaded_matchit = true
g.loaded_netrwFileHandlers = true
g.loaded_netrwPlugin = true
g.loaded_netrwSettings = true
g.loaded_remote_plugins = true
g.loaded_tar = true
g.loaded_tarPlugin = true
g.loaded_zip = true
g.loaded_zipPlugin = true
g.loaded_vimball = true
g.loaded_vimballPlugin = true
