# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Terminal
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# Catppuccin theme (v2 config)
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_current_number_color "#89dceb"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_flags "none"
set -g @catppuccin_pane_active_border_style "fg=#89dceb"

set -g @catppuccin_status_left_separator ""
set -g @catppuccin_status_middle_separator ""
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_connect_separator "no"

set -g status-position top
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_directory} #{E:@catppuccin_status_session}"
set -g status-right-length 100

# Start windows and pane numbering at 1
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
setw -g pane-base-index 1

# Enable mouse mode
set -g mouse on

# Remap `Prefix` key from `C-b` to `C-f`
# unbind C-b
# set -g prefix C-f
# bind C-f send-prefix

# Split window binds
unbind "\""
unbind "\%"
bind -T prefix C-s split-window -v -c "#{pane_current_path}"
bind -T prefix C-v split-window -h -c "#{pane_current_path}"

# Set copy mode to use vi key bindings
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key v copy-mode

# Resize pane with hjkl
bind -r h resize-pane -L 4
bind -r j resize-pane -D 4
bind -r k resize-pane -U 4
bind -r l resize-pane -R 4

bind-key r command-prompt "rename-window %%"

# This is a workaround for https://github.com/tmux/tmux/issues/3705
# which messes up my scroll using bacon: https://github.com/Canop/bacon/issues/174
bind-key -n WheelUpPane {
  if-shell -F '#{mouse_any_flag}' {
      send-keys -M
  } {
    if-shell -F '#{alternate_on}' {
      send-keys Up
    } {
      copy-mode -e
    }
  }
}
bind-key -n WheelDownPane {
  if-shell -F '#{mouse_any_flag}' {
      send-keys -M
  } {
      send-keys Down
  }
}

run '~/.tmux/plugins/tpm/tpm'
