set-option -g @plugin "catppuccin/tmux"
set-option -g @plugin "christoomey/vim-tmux-navigator"
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Theme
set-option -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
set-option -g status-position top

set-option -g @catppuccin_window_left_separator ""
set-option -g @catppuccin_window_right_separator " "
set-option -g @catppuccin_window_middle_separator " █"
set-option -g @catppuccin_window_number_position "right"

set-option -g @catppuccin_window_default_fill "number"
set-option -g @catppuccin_window_default_text "#W"

set-option -g @catppuccin_window_current_fill "number"
set-option -g @catppuccin_window_current_text "#W"

set-option -g @catppuccin_status_modules_right "directory user host session"
set-option -g @catppuccin_status_left_separator " "
set-option -g @catppuccin_status_right_separator ""
set-option -g @catppuccin_status_right_separator_inverse "no"
set-option -g @catppuccin_status_fill "icon"
set-option -g @catppuccin_status_connect_separator "no"

# Start windows and pane numbering at 1
set-option -g base-index 1
set-option -g pane-base-index 1
set-option -g renumber-windows on
set-window-option -g pane-base-index 1

# Enable mouse mode
set-option -g mouse on

# Remap `Prefix` key from `C-b` to `C-f`
# unbind C-b
# set-option -g prefix C-f
# bind C-f send-prefix

# Split window binds
unbind "\""
unbind "\%"
bind -T prefix C-s split-window -v -c "#{pane_current_path}"
bind -T prefix C-v split-window -h -c "#{pane_current_path}"

# Set copy mode to use vi key bindings
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key v copy-mode

# Resize pane with hjkl
bind -r h resize-pane -L 4
bind -r j resize-pane -D 4
bind -r k resize-pane -U 4
bind -r l resize-pane -R 4

bind-key r command-prompt "rename-window %%"

# This is a workaround for https://github.com/tmux/tmux/issues/3705
# which messes up my scroll using bacon: https://github.com/Canop/bacon/issues/174
bind-key -n WheelUpPane {
  if-shell -F '#{mouse_any_flag}' {
      send-keys -M
  } {
    if-shell -F '#{alternate_on}' {
      send-keys Up
    } {
      copy-mode -e
    }
  }
}
bind-key -n WheelDownPane {
  if-shell -F '#{mouse_any_flag}' {
      send-keys -M
  } {
      send-keys Down
  }
}

run '/opt/homebrew/opt/tpm/share/tpm/tpm'
